---
- hosts: hostservers
  become: yes
  become_method: sudo
  remote_user: spider7
  vars:
    - tomcat_url : "https://downloads.apache.org/tomcat/tomcat-9/v9.0.41/bin/apache-tomcat-9.0.41.tar.gz"
    - tomcat_package : "apache-tomcat-9.0.41"

  tasks:
    - name : upadte source list
      command: apt update
    - name: Update repos
      apt:
        name: "*"
        state: latest
    - name: Install required Jdk
      apt:
        name: openjdk-11-jdk
        state: present
    - name: Downloading tomcat
      get_url:
        url: "{{tomcat_url}}"
        dest: /usr/local
    - name: Extracting Tomcat
      unarchive:
        src: "/usr/local/{{tomcat_package}}.tar.gz"
        dest: /usr/local
        remote_src: yes
    - name: Renaming tomcat home
      command: mv /usr/local/{{tomcat_package}} /usr/local/tomcat
    - name: running tomcat service
      shell: nohup /usr/local/tomcat/bin/startup.sh &
    - name:
      copy:
         src: /var/lib/jenkins/workspace/HelloWorld/target/HelloWorld-1.0.0.war
         dest: /usr/local/tomcat/webapps/
